# Generated by Django 5.1.6 on 2025-02-05 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_by', models.BigIntegerField(blank=True, null=True)),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'st_currencies',
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z]{3}$')), name='code_format_check'), models.CheckConstraint(condition=models.Q(('name__regex', '^[A-Z][a-z]*( [A-Z][a-z]*)*$')), name='name_format_check')],
            },
        ),
    ]
